### ISSUE TITLE
Consider switching to glibc base image?

### ISSUE THREAD

**Issue by TheNicholasNick** [wodby/ruby#2]
bundler can't distinguish between variations of muslc/glibc so if any project needs libv8 this whole stack is useless.

https://github.com/cowboyd/libv8/issues/271

**Comment by PavelPrischepa** [comment]
Hi @SoreGums, actually we don't consider migrating from Alpine.

**Comment by pprishchepa** [comment]
Hi SoreGums, does adding `libc-dev` solve the issue for you?

**Comment by TheNicholasNick** [comment]
that didn't work - bummer.

yeah after having gone through switching this to [debian:stretch](https://github.com/soregums/ruby) what you guys have built on Alpine is awesome!

I'm just going to run this Debian stretch ruby image for dev and then come prod will figure out how to build the libv8 gem from source and call it libv8 and it'll work fine on Alpine.

closing :)
